### PR TITLE
Table of contents bug

### LINKED ISSUE #626: Table of Contents often doesn't update to reflect content of page
**Describe the bug**
The table of contents in Code pages often doesn't update when changing between different pages.

**To Reproduce**
1. Got to a page like https://design.infor.com/code/ids-enterprise/latest/typography
    * See TOC with contents like "Font Family"
2. Click on "Alerts" in sidebar
    * See that the TOC still has "Font Family" and no headings related to content from the current page

**Expected behavior**
Expected behavior is that the TOC updates according to each page and is blank if there is no content structure.

**Screenshots**

**Platform**
 - Device (if applicable) [e.g. iPhone 6 or Samsung Galaxy S6]
 - OS Version: [e.g. Windows 10 or iOS 8]
 - Browser Name [e.g. chrome, safari, stock browser]
 - Browser Version [e.g. 22, 66.0.3359.181 (Official Build) (64-bit)]

**Additional context**

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Fixes issue where TOC was not loading in time on route change.
Now, using regex on the payload to search for `<h2>`'s with an `id`, then extracting the id and text to build the TOC.
Previously was querying the DOM to extract `<h2>`'s, but the timing was causing the TOC to build based on the previous route instead of the current one.

**Related github/jira issue (required)**:
closes #626

### CODE REVIEW

File: src/web/src/app/components/docs-content-page/docs-content-page.component.ts [hunk 1]
```diff
@@ -133,6 +142,34 @@ export class DocsContentPageComponent implements OnInit, OnDestroy {
     });
   }
 
+  createTocItems(item) {
+    const regexId = new RegExp(/id=(?:'|")(.*?)(?:'|")/g);
+    const regexLabel = new RegExp(/(<\/?h2 id=(.[^(?:'|")]+(?:'|")>((.|\n)*?<\/h2>)))/, 'ig');
+    const ids = item.match(regexId);
+    const id = ids[0].replace(/id=(?:'|")/g, '').replace(/(?:'|")$/, '');
+    const labels = item.match(regexLabel);
+    const label = labels[0].replace(/(<\/?h2 id=(.[^(?:'|")]+(?:'|")>))/, '').replace(/<\/h2>/, '');
```
Comment (clepore) [inline src/web/src/app/components/docs-content-page/docs-content-page.component.ts]: This regex is some sorcerer level 💩 .
